wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.10
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711019790.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.7.10
      5: 0.16.4
      8:
      - 5
      10:
      - 3
      13: linux-x86_64
rgb_loss:
  desc: null
  value: 0.23107144236564636
depth_loss:
  desc: null
  value: 0.5123159885406494
geo_loss:
  desc: null
  value: 0.4978875517845154
cross_entropy_loss:
  desc: null
  value: 1.1019974946975708
eikonal_loss:
  desc: null
  value: 0.01227203756570816
loss:
  desc: null
  value: 1.8715065717697144
